// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7n2qQ7qWbaSoTf29w3fMdw
// Component: akW0lIGrcQfh
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HeroSection2 from "../../HeroSection2"; // plasmic-import: ggPVYPkpnqTc/component
import Button from "../../Button"; // plasmic-import: pvEDofsnRpb1/component
import Divider from "../../Divider"; // plasmic-import: Rqd4TOdKp3dG/component
import Textinput from "../../Textinput"; // plasmic-import: FqpIcTR5Xsgw/component
import Navigation from "../../Navigation"; // plasmic-import: 9zyDsnm4C_yB/component
import ValuesSection3 from "../../ValuesSection3"; // plasmic-import: dfdRrXh2sQb2/component
import Valueprop from "../../Valueprop"; // plasmic-import: e2ZXYpC2HACl/component
import ValuesSection2Dark from "../../ValuesSection2Dark"; // plasmic-import: cCwkE_yl5lBB/component
import ListItem from "../../ListItem"; // plasmic-import: TNcsFv7azbn4/component
import PricingSection3 from "../../PricingSection3"; // plasmic-import: 1QzA-iTEF4nu/component
import ShopBanners from "../../ShopBanners"; // plasmic-import: TTSbv7Byagwq/component
import Banner from "../../Banner"; // plasmic-import: 7LgegPMTI35O/component
import LogoCloudSection2 from "../../LogoCloudSection2"; // plasmic-import: 5ZoT700l-v8r/component
import TestimonialsSection1 from "../../TestimonialsSection1"; // plasmic-import: 7-Isjg5BxQT7/component
import Testimonial from "../../Testimonial"; // plasmic-import: qfRWXAuACcrP/component
import CallToActionSection1 from "../../CallToActionSection1"; // plasmic-import: PH1uqmC286I-/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 7JAIBK6bs3Uw/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: 7n2qQ7qWbaSoTf29w3fMdw/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: akW0lIGrcQfh/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 2UUbeI57eEFB/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: EIx_50oXLXpV/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: mMGJziJ_xoVs/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: Cewdw1H25Xz0/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: RMg8AZrxzN6G/icon
import Icon17Icon from "./icons/PlasmicIcon__Icon17"; // plasmic-import: a3S8_12MIoVU/icon
import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: obXil6sG5_gv/icon
import image13NjMtOxJcmP5K from "./images/image13.svg"; // plasmic-import: NjMtOXJcmP5k/picture
import loomsvg2ILCtQmw7Xxvv from "./images/loomsvg2.svg"; // plasmic-import: iLCtQMW7XXVV/picture
import strapisvg2WIdvep7XtZsO from "./images/strapisvg2.svg"; // plasmic-import: wIdvep7XTZsO/picture
import segmentsvg2AvkYeRcKpLta from "./images/segmentsvg2.svg"; // plasmic-import: avkYeRCKpLta/picture
import xstate1SvgT9GsDseDgGl from "./images/xstate1Svg.svg"; // plasmic-import: t9GS_DseDGGl/picture
import mapboxsvg2BEmzGc4Fz5Xr from "./images/mapboxsvg2.svg"; // plasmic-import: bEMZGc4Fz5Xr/picture

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  heroSection2?: p.Flex<typeof HeroSection2>;
  navigation?: p.Flex<typeof Navigation>;
  valuesSection3?: p.Flex<typeof ValuesSection3>;
  h2?: p.Flex<"h2">;
  valuesSection2Dark?: p.Flex<typeof ValuesSection2Dark>;
  pricingSection3?: p.Flex<typeof PricingSection3>;
  shopBanners?: p.Flex<typeof ShopBanners>;
  logoCloudSection2?: p.Flex<typeof LogoCloudSection2>;
  testimonialsSection1?: p.Flex<typeof TestimonialsSection1>;
  callToActionSection1?: p.Flex<typeof CallToActionSection1>;
};

export interface DefaultHomepageProps {
  className?: string;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeroSection2
            data-plasmic-name={"heroSection2"}
            data-plasmic-override={overrides.heroSection2}
            className={classNames("__wab_instance", sty.heroSection2)}
            foreground={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__eaYs)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__lflxT)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__yjB3X)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__sxwG
                        )}
                      >
                        {"Updated!"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__rawai
                      )}
                    >
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                      >
                        <React.Fragment>{"Designs that "}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecoration: "underline" }}
                        >
                          {"adapt"}
                        </span>
                      </span>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__hoicb
                      )}
                    >
                      {
                        "Orci dui condimentum rutrum laoreet hac purus porta sem sem a vivamus a posuere vel molestie."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___76ORf)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__r0XiZ
                      )}
                      darkGray={"darkGray" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___7Xy2
                          )}
                        >
                          {"Start now ->"}
                        </div>
                      }
                    />

                    <Button
                      bgDifference={"bgDifference" as const}
                      className={classNames("__wab_instance", sty.button__sRzQ)}
                      darkGray={"darkGray" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__rIqD
                          )}
                        >
                          {"Learn more…"}
                        </div>
                      }
                    />
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__erZr)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox___2JsjM)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__xJyR)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__bhgV
                        )}
                      >
                        {"Sign up with"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__gvlG4
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__wtBf6
                          )}
                          ouline={"ouline" as const}
                          slot={"Apple"}
                          startIcon={"startIcon" as const}
                        />

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__pYDth
                          )}
                          ouline={"ouline" as const}
                          slot={"Google"}
                          startIcon={"startIcon" as const}
                        >
                          <Icon6Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__ubZa5
                            )}
                            role={"img"}
                          />
                        </Button>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox___2Xbqq
                        )}
                      >
                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider__n2IXw
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__iOq7W
                          )}
                        >
                          {"Or"}
                        </div>

                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider__aDlT
                          )}
                        />
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__t5Km
                        )}
                      >
                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__uza7Z
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput___48TgC
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__ru14R
                          )}
                        />
                      </p.Stack>

                      <Button
                        children2={
                          <Icon5Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__qgg7H
                            )}
                            role={"img"}
                          />
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.button__zQFer
                        )}
                        colors={"indigo" as const}
                        slot={"Start your account"}
                      />
                    </p.Stack>

                    <Divider
                      className={classNames(
                        "__wab_instance",
                        sty.divider___2Lsek
                      )}
                    />

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__rCbao)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___6Kjfk
                        )}
                      >
                        {
                          "A cras sagittis odio vestibulum pulvinar a eget hendrerit id vestibulum a leo sociosqu dictumst dictumst natoque magnis parturient."
                        }
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          >
            <Navigation
              data-plasmic-name={"navigation"}
              data-plasmic-override={overrides.navigation}
              className={classNames("__wab_instance", sty.navigation)}
              hideCta={"hideCta" as const}
              slot={
                <React.Fragment>
                  <Button
                    className={classNames("__wab_instance", sty.button__yeQd)}
                    link={"#services" as const}
                    navLink={"navLink" as const}
                    slot={"Services"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__xy6He)}
                    link={"#features" as const}
                    navLink={"navLink" as const}
                    slot={"Features"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__xu8Ov)}
                    link={"#pricing" as const}
                    navLink={"navLink" as const}
                    slot={"Pricing"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___74ZH)}
                    link={"#testimonials" as const}
                    navLink={"navLink" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__kJsJ4
                        )}
                      >
                        {"Testimonials"}
                      </div>
                    }
                  />

                  <Button
                    children2={
                      <React.Fragment>
                        <IconIcon
                          className={classNames(defaultcss.all, sty.svg__iyaoe)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__a4PPa
                          )}
                        >
                          {"Log in"}
                        </div>
                      </React.Fragment>
                    }
                    className={classNames("__wab_instance", sty.button__lhqVv)}
                    navLink={"navLink" as const}
                    slot={null}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__rr4G)}
                    darkGray={"darkGray" as const}
                    slot={"Sign up"}
                  />
                </React.Fragment>
              }
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___1Qza)}
                role={"img"}
                src={image13NjMtOxJcmP5K}
              />
            </Navigation>
          </HeroSection2>

          <div
            className={classNames(defaultcss.all, sty.freeBox__tXwgs)}
            id={"services" as const}
          >
            <ValuesSection3
              data-plasmic-name={"valuesSection3"}
              data-plasmic-override={overrides.valuesSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__zWdq9)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__sPrdi)}
                    >
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          defaultcss.h2,
                          defaultcss.__wab_text,
                          sty.h2
                        )}
                      >
                        {"Proposing values"}
                      </h2>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__shodi
                      )}
                    >
                      {
                        "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___8B8Kq)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___792V6
                      )}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__qnjor
                        )}
                        flat={"flat" as const}
                        slot={
                          "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___0Lfwu
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Powerful"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__ayBLk
                        )}
                        flat={"flat" as const}
                        slot={
                          "Consequat scelerisque a eros taciti nisl a sodales."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__zo7P4
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Faster"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__l4JkF
                        )}
                        flat={"flat" as const}
                        slot={"At ut condimentum amet adipiscing ac diam a."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__lsSaF
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Best and brightest"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__dJiB
                        )}
                        flat={"flat" as const}
                        slot={
                          "Donec purus nec vestibulum volutpat vivamus vulputate suspendisse."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__wcVxu
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__msSj
                          )}
                        >
                          {"Dynamic range"}
                        </div>
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__rda9J)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___9R0Wa
                      )}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop___5QGzl
                        )}
                        flat={"flat" as const}
                        slot={
                          "Commodo pretium himenaeos nisi potenti ad in ante."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__oSf4G
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__s8Slw
                          )}
                        >
                          {"Portable"}
                        </div>
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__feKR
                        )}
                        flat={"flat" as const}
                        slot={"Magna ullamcorper ut arcu nisi a per facilisis."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__eqMpg
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Production-ready"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__mLPxo
                        )}
                        flat={"flat" as const}
                        slot={
                          "Ac lobortis praesent sagittis dictumst fermentum vestibulum nunc."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___9ViS5
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Magical"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__ydIyI
                        )}
                        flat={"flat" as const}
                        slot={
                          "A parturient mi suspendisse nisl inceptos nullam a."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__gGAjT
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Accessible"}
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.freeBox__kv34)}
            id={"features" as const}
          >
            <ValuesSection2Dark
              data-plasmic-name={"valuesSection2Dark"}
              data-plasmic-override={overrides.valuesSection2Dark}
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.freeBox___1Omlh)}
            id={"pricing" as const}
          >
            <PricingSection3
              data-plasmic-name={"pricingSection3"}
              data-plasmic-override={overrides.pricingSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__c2Os)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__agdQo)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__j9Roh
                        )}
                      >
                        {"Pricing plans"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___13Vgw
                      )}
                    >
                      {
                        "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__dgPji)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___6T1BI
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__v94Cf
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___7YTxr
                          )}
                        >
                          {"Starter"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__cgxWd
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__ktURm
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__cvDq1
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__g3KwN
                              )}
                            >
                              {"8"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__diznx
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__etdDs
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__fzzJ4
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__khMef
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___2Zj3U
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__jDqb
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__x5IHz
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___3Tbck
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={"Mus consequat a justo"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__wxyUh
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__yl8Q
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white" as const}
                          extraSmallShadow={"extraSmallShadow" as const}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__lk1I
                              )}
                            >
                              {"Buy starter"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__j51K0)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__k4Aff
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__odOGn
                          )}
                        >
                          {"Pro"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__ypmZl
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__mbLSz
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__gsrXr
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__qh1Aw
                              )}
                            >
                              {"16"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox___4OJd8
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider___6XIAm
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__twyqk
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__qznEh
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__dsU4E
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "Ligula primis mollis sem dignissim semper lectus parturient"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___3YpU
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__eVtT
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__vtoBj
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.freeBox___6JfL
                                )}
                              >
                                {
                                  "A curabitur dignissim pharetra porta suscipit"
                                }
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__j9U
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__pmgnl
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__wuksy
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "Condimentum diam a et sapien praesent potenti torquent a eros"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__c34R3
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__cgnZd
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__tz0F
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.freeBox__qtRDn
                                )}
                              >
                                {"Conubia in hac eu elementum sodales"}
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__vf1Ed
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__lWPw
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"green" as const}
                          extraSmallShadow={"extraSmallShadow" as const}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__vq9Yh
                              )}
                            >
                              {"Buy pro"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__kbQr)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__zpssl
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__g1DHz
                          )}
                        >
                          {"Team"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__gzAvk
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__xhQoI
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__qTmrM
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__ilkTe
                              )}
                            >
                              {"10"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__goHOz
                            )}
                          >
                            {"/member"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__cwqM8
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__i527
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__yZLwy
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__aAjW
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={"Ad nam curae a potenti platea"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___9XSRv
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__gXsj7
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__kz8Js
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "A adipiscing scelerisque pretium consectetur sem"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__yu1J8
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__qedEk
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white" as const}
                          extraSmallShadow={"extraSmallShadow" as const}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__vdu4T
                              )}
                            >
                              {"Buy team"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <ShopBanners
            data-plasmic-name={"shopBanners"}
            data-plasmic-override={overrides.shopBanners}
            className={classNames("__wab_instance", sty.shopBanners)}
          >
            <Banner
              className={classNames("__wab_instance", sty.banner__ucvvA)}
              left={
                <React.Fragment>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__hYgpU
                    )}
                  >
                    {"Sunglasses Collection"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__ikFeg
                    )}
                  >
                    {"Get 25% off on selected items"}
                  </div>

                  <Button
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__aw998
                        )}
                      >
                        {"Go to collection ->"}
                      </div>
                    }
                  />
                </React.Fragment>
              }
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__udvMj)}
            >
              <Banner
                className={classNames("__wab_instance", sty.banner__r9XKl)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__hEz82
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__qgPLe
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___60STv
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__yAdYt)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1463100099107-aa0980c362e6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80" as const
                  }
                />
              </Banner>

              <Banner
                className={classNames("__wab_instance", sty.banner__nkQxv)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___3GJ7O
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__a3PyR
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__ybRcO
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__mg8X5)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1554568218-0f1715e72254?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1834&q=80" as const
                  }
                />
              </Banner>
            </p.Stack>
          </ShopBanners>

          <LogoCloudSection2
            data-plasmic-name={"logoCloudSection2"}
            data-plasmic-override={overrides.logoCloudSection2}
            className={classNames("__wab_instance", sty.logoCloudSection2)}
          />

          <div
            className={classNames(defaultcss.all, sty.freeBox__lFqL)}
            id={"testimonials" as const}
          >
            <TestimonialsSection1
              data-plasmic-name={"testimonialsSection1"}
              data-plasmic-override={overrides.testimonialsSection1}
            >
              <Testimonial
                className={classNames(
                  "__wab_instance",
                  sty.testimonial___2NfLh
                )}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__o1P)}
                    role={"img"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj" as const
                    }
                  />
                }
              />

              <Testimonial
                className={classNames(
                  "__wab_instance",
                  sty.testimonial___7YsPj
                )}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__dUo8G)}
                    role={"img"}
                    src={
                      "https://tv-fanatic-res.cloudinary.com/iu/s--eXCbHIe1--/t_teaser_wide/cs_srgb,f_auto,fl_strip_profile.lossy,q_auto:420/v1371156342/elaine-benes-picture.png" as const
                    }
                  />
                }
                slot2={"Elaine Benes"}
                slot3={"Editor, Pendant Publishing"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__vsy3I
                  )}
                >
                  {'"Vestibulum lacinia varius habitant dis aenean.'}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__ldfZx
                  )}
                >
                  {
                    'A parturient non ultricies a parturient leo a nascetur at consectetur turpis praesent mus ornare nulla posuere vel parturient."'
                  }
                </div>
              </Testimonial>

              <Testimonial
                className={classNames(
                  "__wab_instance",
                  sty.testimonial___7JgBa
                )}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__woCCj)}
                    role={"img"}
                    src={
                      "https://i.pinimg.com/originals/87/d7/7d/87d77d68368fe5361d535b51cc5af09a.jpg" as const
                    }
                  />
                }
                slot2={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__p75Dg
                    )}
                  >
                    {"Woody Boyd"}
                  </div>
                }
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__amGG
                    )}
                  >
                    {"Assistant Bartender, Cheers"}
                  </div>
                }
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__sxKBq
                  )}
                >
                  {
                    '"A ullamcorper etiam gravida a non maecenas ac parturient lectus vestibulum nam."'
                  }
                </div>
              </Testimonial>

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__saXIb)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__wryQb)}
                    role={"img"}
                    src={
                      "https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters_opt/p-fresh-randall-park.jpg" as const
                    }
                  />
                }
                slot2={"Louis Huang"}
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___0OhaA
                    )}
                  >
                    {"Restaurant Owner, Cattleman's Ranch"}
                  </div>
                }
              >
                {
                  '"Purus dis a primis rhoncus blandit velit suspendisse porta at ullamcorper suscipit a scelerisque sed pharetra facilisi vitae."'
                }
              </Testimonial>
            </TestimonialsSection1>
          </div>

          <CallToActionSection1
            data-plasmic-name={"callToActionSection1"}
            data-plasmic-override={overrides.callToActionSection1}
            className={classNames("__wab_instance", sty.callToActionSection1)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "heroSection2",
    "navigation",
    "valuesSection3",
    "h2",
    "valuesSection2Dark",
    "pricingSection3",
    "shopBanners",
    "logoCloudSection2",
    "testimonialsSection1",
    "callToActionSection1"
  ],
  heroSection2: ["heroSection2", "navigation"],
  navigation: ["navigation"],
  valuesSection3: ["valuesSection3", "h2"],
  h2: ["h2"],
  valuesSection2Dark: ["valuesSection2Dark"],
  pricingSection3: ["pricingSection3"],
  shopBanners: ["shopBanners"],
  logoCloudSection2: ["logoCloudSection2"],
  testimonialsSection1: ["testimonialsSection1"],
  callToActionSection1: ["callToActionSection1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  heroSection2: typeof HeroSection2;
  navigation: typeof Navigation;
  valuesSection3: typeof ValuesSection3;
  h2: "h2";
  valuesSection2Dark: typeof ValuesSection2Dark;
  pricingSection3: typeof PricingSection3;
  shopBanners: typeof ShopBanners;
  logoCloudSection2: typeof LogoCloudSection2;
  testimonialsSection1: typeof TestimonialsSection1;
  callToActionSection1: typeof CallToActionSection1;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroSection2: makeNodeComponent("heroSection2"),
    navigation: makeNodeComponent("navigation"),
    valuesSection3: makeNodeComponent("valuesSection3"),
    h2: makeNodeComponent("h2"),
    valuesSection2Dark: makeNodeComponent("valuesSection2Dark"),
    pricingSection3: makeNodeComponent("pricingSection3"),
    shopBanners: makeNodeComponent("shopBanners"),
    logoCloudSection2: makeNodeComponent("logoCloudSection2"),
    testimonialsSection1: makeNodeComponent("testimonialsSection1"),
    callToActionSection1: makeNodeComponent("callToActionSection1"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
