// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7n2qQ7qWbaSoTf29w3fMdw
// Component: 1QzA-iTEF4nu
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Divider from "../../Divider"; // plasmic-import: Rqd4TOdKp3dG/component
import Valueprop from "../../Valueprop"; // plasmic-import: e2ZXYpC2HACl/component
import Button from "../../Button"; // plasmic-import: pvEDofsnRpb1/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: 7n2qQ7qWbaSoTf29w3fMdw/projectcss
import * as sty from "./PlasmicPricingSection3.module.css"; // plasmic-import: 1QzA-iTEF4nu/css

import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: Cewdw1H25Xz0/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 2UUbeI57eEFB/icon

export type PlasmicPricingSection3__VariantMembers = {};

export type PlasmicPricingSection3__VariantsArgs = {};
type VariantPropType = keyof PlasmicPricingSection3__VariantsArgs;
export const PlasmicPricingSection3__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPricingSection3__ArgsType = {
  foreground?: React.ReactNode;
};

type ArgPropType = keyof PlasmicPricingSection3__ArgsType;
export const PlasmicPricingSection3__ArgProps = new Array<ArgPropType>(
  "foreground"
);

export type PlasmicPricingSection3__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  foreground?: p.Flex<"div">;
};

export interface DefaultPricingSection3Props {
  foreground?: React.ReactNode;
  className?: string;
}

function PlasmicPricingSection3__RenderFunc(props: {
  variants: PlasmicPricingSection3__VariantsArgs;
  args: PlasmicPricingSection3__ArgsType;
  overrides: PlasmicPricingSection3__OverridesType;
  dataFetches?: PlasmicPricingSection3__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(defaultcss.all, sty.freeBox)}
      />

      <p.Stack
        as={"div"}
        data-plasmic-name={"foreground"}
        data-plasmic-override={overrides.foreground}
        hasGap={true}
        className={classNames(defaultcss.all, sty.foreground)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__qbKbD)}
              >
                <div
                  className={classNames(defaultcss.all, sty.freeBox___0Lm3G)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__t62DL
                    )}
                  >
                    {"Pricing plans"}
                  </div>
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__kCVqK
                  )}
                >
                  {
                    "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                  }
                </div>
              </p.Stack>

              <div className={classNames(defaultcss.all, sty.freeBox__b2SY1)}>
                <div className={classNames(defaultcss.all, sty.freeBox__j7FdU)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__cH88)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__sWt3
                      )}
                    >
                      {"Starter"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__yn2C)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__sdpjC
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__uZ12
                          )}
                        >
                          {"$"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___1Thja
                          )}
                        >
                          {"8"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__ovfxE
                        )}
                      >
                        {"/month"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <Divider
                    className={classNames("__wab_instance", sty.divider__eo3Gy)}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__xgWs8)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__tpFsE)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__eVw6D
                        )}
                        flatIcon={"flatIcon" as const}
                        justDescription={"justDescription" as const}
                        slot={
                          "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___7Xrjx
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__iw5Vb
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__dwhmA
                        )}
                        flatIcon={"flatIcon" as const}
                        justDescription={"justDescription" as const}
                        slot={"Mus consequat a justo"}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__bGX0
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__ru1Hb
                            )}
                            role={"img"}
                          />
                        }
                      />
                    </p.Stack>

                    <Button
                      colors={"white" as const}
                      extraSmallShadow={"extraSmallShadow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__myKR
                          )}
                        >
                          {"Buy starter"}
                        </div>
                      }
                    />
                  </p.Stack>
                </div>

                <div className={classNames(defaultcss.all, sty.freeBox__itmL4)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__gjnez)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__c0Xpi
                      )}
                    >
                      {"Pro"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__tHjkC)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__qOWv
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___4NquQ
                          )}
                        >
                          {"$"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___7Irfp
                          )}
                        >
                          {"16"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__vOfcY
                        )}
                      >
                        {"/month"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <Divider
                    className={classNames("__wab_instance", sty.divider__oVkpa)}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__okhvm)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__fwZZg)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__rdmU0
                        )}
                        flatIcon={"flatIcon" as const}
                        justDescription={"justDescription" as const}
                        slot={
                          "Ligula primis mollis sem dignissim semper lectus parturient"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__mtxmu
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___6Ba9Q
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__pr58L
                        )}
                        flatIcon={"flatIcon" as const}
                        justDescription={"justDescription" as const}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__szHdb
                            )}
                          >
                            {"A curabitur dignissim pharetra porta suscipit"}
                          </div>
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__ztL8T
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__sM5Gj
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__gNV3
                        )}
                        flatIcon={"flatIcon" as const}
                        justDescription={"justDescription" as const}
                        slot={
                          "Condimentum diam a et sapien praesent potenti torquent a eros"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__atfB
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___5ZBa
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__cPLrT
                        )}
                        flatIcon={"flatIcon" as const}
                        justDescription={"justDescription" as const}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__hXd3Y
                            )}
                          >
                            {"Conubia in hac eu elementum sodales"}
                          </div>
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__bpEsn
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__edymt
                            )}
                            role={"img"}
                          />
                        }
                      />
                    </p.Stack>

                    <Button
                      colors={"green" as const}
                      extraSmallShadow={"extraSmallShadow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__tBqe
                          )}
                        >
                          {"Buy pro"}
                        </div>
                      }
                    />
                  </p.Stack>
                </div>

                <div className={classNames(defaultcss.all, sty.freeBox__mfsh0)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__eqOcG)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__i4B7E
                      )}
                    >
                      {"Team"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__zFwu6)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__o76Fu
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__rdudm
                          )}
                        >
                          {"$"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__ttHvT
                          )}
                        >
                          {"10"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__pkChr
                        )}
                      >
                        {"/member"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <Divider
                    className={classNames(
                      "__wab_instance",
                      sty.divider___4HhPe
                    )}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__gdUOh)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__gKopi)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__xfzW
                        )}
                        flatIcon={"flatIcon" as const}
                        justDescription={"justDescription" as const}
                        slot={"Ad nam curae a potenti platea"}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___5GbPd
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__o8Yk
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__hvpSv
                        )}
                        flatIcon={"flatIcon" as const}
                        justDescription={"justDescription" as const}
                        slot={
                          "A adipiscing scelerisque pretium consectetur sem"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__v6MxJ
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__gFn0K
                            )}
                            role={"img"}
                          />
                        }
                      />
                    </p.Stack>

                    <Button
                      colors={"white" as const}
                      extraSmallShadow={"extraSmallShadow" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__b0Kt9
                          )}
                        >
                          {"Buy team"}
                        </div>
                      }
                    />
                  </p.Stack>
                </div>
              </div>
            </React.Fragment>
          ),
          value: args.foreground
        })}
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "foreground"],
  freeBox: ["freeBox"],
  foreground: ["foreground"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  foreground: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPricingSection3__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPricingSection3__VariantsArgs;
    args?: PlasmicPricingSection3__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicPricingSection3__Fetches;
  } & Omit<PlasmicPricingSection3__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPricingSection3__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPricingSection3__ArgProps,
      internalVariantPropNames: PlasmicPricingSection3__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicPricingSection3__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPricingSection3";
  } else {
    func.displayName = `PlasmicPricingSection3.${nodeName}`;
  }
  return func;
}

export const PlasmicPricingSection3 = Object.assign(
  // Top-level PlasmicPricingSection3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    foreground: makeNodeComponent("foreground"),

    // Metadata about props expected for PlasmicPricingSection3
    internalVariantProps: PlasmicPricingSection3__VariantProps,
    internalArgProps: PlasmicPricingSection3__ArgProps
  }
);

export default PlasmicPricingSection3;
/* prettier-ignore-end */
